### ISSUE TITLE
late loading for IO calls...

### ISSUE THREAD

**Issue by gedw99** [sebastianpacurar/geographic-data-ui#42]
Great example of the gio Component. I like it too for bootstrapping !!

Also the folder and golang structure is very clean in terms of separation of concerns.

I noticed the http rest call blocks the GUI. This is for the 2nd example that pulls the country data.

If you kill your internet connection or just buffer it, you will see the GUI just does not load. Did for me :)

There has been a fair bit of discussion about this on the gio slack....

Its here: https://github.com/sebastianpacurar/gioui-experiment/blob/main/apps/geography/data/countries.go#L173

Some options....

@Inkeliz has done some work on helping in this area. ccing him...

1. That call is not protected a go routine.. I wonder if it might help ?

2. https://github.com/Inkeliz/giostorage is a cache for Web and non Web. Might help i think to a degree ?

**Comment by sebastianpacurar** [comment]
Thanks for the highlights!
Just tried the same steps you've mentioned and it happened. I used a pretty naive way of decoding the flags from an already existing folder containing them as .png, and I missed this scenario after switching to the current config.
I'll look into it, also thanks for the **giostorage** reference :)

**Comment by gedw99** [comment]
no worries :)  

i also think that the you need to paginate and have less on each screen to keep the GUi snappy.  I noticed myself that GIO does not like holding too much data at the GUi level. It slows things down. Its best when its doing a fair bit of IO to a client cache and then hitting server on a cache miss. Seems to be the golden path GIO...  Of course each project is different, but just what i noticed using GIO for different things.

I have been using Flat buffers and GRPC with GIO, to keep things light as possible. Flat Buffers is a good match as its lighter than grpc.

here is an example if your curious: https://github.com/tsavola/giobuffers/blob/f2ab47e946/apps/hello/hello.go#L33
